disabled_rules:
  - trailing_comma
  - redundant_optional_initialization
  - vertical_whitespace_opening_braces

included:
  - Sources
  - Tests

excluded:
  - .build

line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

identifier_name:
  min_length: 2
  max_length: 40

type_name:
  min_length: 3
  max_length: 40