name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  SWIFT_VERSION: '6.0'

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ env.SWIFT_VERSION }}
    
    - name: Show Swift version
      run: swift --version
    
    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v
    
    - name: Run tests with coverage
      run: |
        swift test --enable-code-coverage
        
    - name: Generate coverage report
      if: matrix.os == 'macos-latest'
      run: |
        cd .build/debug
        BINARY_PATH=$(find . -name '*.xctest' -type f | head -n 1)/Contents/MacOS/*Tests
        PROFDATA_PATH=$(find . -name 'default.profdata' -type f | head -n 1)
        xcrun llvm-cov export \
          -format="lcov" \
          -instr-profile=$PROFDATA_PATH \
          $BINARY_PATH > ../../coverage.lcov
        cd ../..
    
    - name: Upload coverage to Codecov
      if: matrix.os == 'macos-latest'
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.lcov
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  lint:
    name: SwiftLint
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
    
    - name: Run SwiftLint
      run: swiftlint --strict

  # Documentation generation disabled for now
  # Will re-enable once Swift-DocC is more stable with Swift 6.0

  release:
    name: Create Release
    needs: [test, lint]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        draft: false
        prerelease: false